const { decEnergy, incEnergy } = require('./src/energy')
const {incHunger, decHunger} = require('./src/hunger')
const { food } = require('./src/food')
const { get } = require('./src/stats')
const { applyTimeReward } = require('./src/timeReward')
const { rewardEffort } = require('./src/reward')
const { actions } = require('./src/actions')
console.log('Current Stats:', get())

const act = actions()
const eat = food()
