const { decEnergy, incEnergy } = require('./src/energy')
const {incHunger, decHunger} = require('./src/hunger')
const { food } = require('./src/food')
const { get } = require('./src/stats')
const {rewardEffort} = require('./src/reward')
rewardEffort(2)
console.log('Current Stats:', get())